project:
  type: book

book:
  title: "SpaceBooklet"
  author: "Your Name"
  chapters:
    - index.qmd
    - intro.qmd
    - Getting_Started.qmd
    - Fundamentals_of_Digital_Work.qmd
    - Essential_Skills_and_Techniques.qmd
    - Advanced_Digital_Techniques.qmd
    - Case_Studies_and_Real_World_Applications.qmd
    - Troubleshooting_and_Problem_Solving.qmd
    - Exploring_New_Frontiers.qmd
    - Conclusion.qmd
    - Appendices.qmd
